### ISSUE TITLE
AndroidDebugTest returns Failed, error in description

### ISSUE THREAD

**Issue by Moderbord** [lolobosse/Sentinel#2]
<pre><code> de.tum.in.i22.sentinel.android.app.AppPickingProcessTest > testNumberOfPackages[SM-G900F - 5.0] FAILED
        junit.framework.AssertionFailedError: Number of packages is not consistent expected:<345> but was:<47>
        at junit.framework.Assert.fail(Assert.java:50)
:sentinel:connectedDebugAndroidTest FAILED <code><pre>

**Comment by lolobosse** [comment]
It is on your device right?

I think the regex is still not fully correct, I will look at it but can you print the list you have by adding a log [there](https://github.com/lolobosse/DroidForce/blob/policyUI/sentinel/src/androidTest/java/de/tum/in/i22/sentinel/android/app/AppPickingProcessTest.java#L32) (`cLine`) and [here](https://github.com/lolobosse/DroidForce/blob/policyUI/sentinel/src/main/java/de/tum/in/i22/sentinel/android/app/package_getter/PackageGetter.java#L56) with `cLine` also and different TAG and publish the two **COMPLETE** list here?

**Comment by Moderbord** [comment]
[AppPicker LOG.txt](https://github.com/lolobosse/DroidForce/files/93598/AppPicker.LOG.txt)
[PackageGetter LOG.txt](https://github.com/lolobosse/DroidForce/files/93599/PackageGetter.LOG.txt)
